---
- name: Install development tools from system
  become: true
  ansible.builtin.package:
    name:
      - clang
      - cmake
      - cppcheck
      - doxygen
      - gcc
      - gcc-c++
      - gcovr
      - gdb
      - lcov
      - make
      - ninja-build
      - valgrind
    state: present

- name: Install development tools from Pip
  become: true
  ansible.builtin.pip:
    name:
      - cpplint
    state: present
