---
- name: Include dependency roles
  ansible.builtin.include_role:
    name: "{{ role }}"
  loop_control:
    loop_var: "role"
  loop:
    - common
    - containerhost
    - virthost

- name: Include C++ development tasks
  ansible.builtin.include_tasks: cpp.yml
