set -g @plugin 'tmux-plugins/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g mouse on

# Keep path when splitting windows
#unbind \"
bind \" split-window -v -c "#{pane_current_path}"
#unbind %
bind % split-window -h -c "#{pane_current_path}"

# vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

TMUX_ACCENT=green

# status line
set -g status-style 'bg=black fg=white'
set -g status-left "#[bg=$TMUX_ACCENT,fg=black,bold] #S #[bg=black] "
set -g status-right-length 50
set -g status-right "#[bg=$TMUX_ACCENT,fg=black,bold] %Y-%m-%d %H:%M "

setw -g window-status-format ' #I:#W '
setw -g window-status-current-format "#[fg=$TMUX_ACCENT,bold] #I:#W "

run '~/.tmux/plugins/tpm/tpm'
