---
- name: Install container tools
  become: true
  ansible.builtin.package:
    name:
      - podman
      - buildah
      - skopeo
    state: present

- name: Install podman-docker
  become: true
  ansible.builtin.package:
    name: podman-docker
    state: present
  ignore_errors: true
