---
- name: Install basic packages
  become: true
  ansible.builtin.package:
    name:
      - git
      - tmux
      - vim
    state: present

- name: Create .ssh dir
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    mode: "700"
    state: directory

- name: Generate ssh keys
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: false

- name: Make vim the default git editor
  community.general.ini_file:
    path: "{{ ansible_env.HOME }}/.gitconfig"
    section: core
    option: editor
    value: vim
    mode: '644'

- name: Install ALE
  ansible.builtin.git:
    depth: 1
    dest: "{{ ansible_env.HOME }}/.vim/pack/git-plugins/start/ale"
    repo: https://github.com/dense-analysis/ale.git

- name: Install TMux Plugin Manager
  ansible.builtin.git:
    depth: 1
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    repo: https://github.com/tmux-plugins/tpm.git

- name: Copy dot files
  ansible.builtin.copy:
    src: "{{ file }}"
    dest: "{{ ansible_env.HOME }}/{{ file }}"
    mode: '644'
  loop_control:
    loop_var: "file"
  loop:
    - .vimrc
    - .tmux.conf
    - .bash_profile
    - .inputrc
