---
- name: Install basic packages
  become: yes
  package:
    name:
      - git
      - tmux
      - vim
    state: latest

- name: Update packages
  become: yes
  package:
    name: '*'
    state: latest

- name: Create .ssh dir
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    mode: "700"
    state: directory

- name: Generate ssh keys
  openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: no

- name: Install keybase (RPM)
  become: yes
  dnf:
    name: https://prerelease.keybase.io/keybase_amd64.rpm
    state: present
  when:
    - ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat'

- block:
  - name: Download keybase (DEB)
    get_url:
      url: https://prerelease.keybase.io/keybase_amd64.deb
      dest: /tmp/keybase_amd64.deb
  - name: Install keybase (DEB)
    become: yes
    apt:
      deb: /tmp/keybase_amd64.deb
      state: present
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Start keybase
  shell:
    cmd: run_keybase -g

- name: Make vim the default git editor
  community.general.ini_file:
    path: "{{ ansible_env.HOME }}/.gitconfig"
    section: core
    option: editor
    value: vim

- name: Install ALE
  git:
    depth: 1
    dest: "{{ ansible_env.HOME }}/.vim/pack/git-plugins/start/ale"
    repo: https://github.com/dense-analysis/ale.git

- name: Install TMux Plugin Manager
  git:
    depth: 1
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    repo: https://github.com/tmux-plugins/tpm.git

- name: Copy dot files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
  loop:
    - .vimrc
    - .tmux.conf
    - .bash_profile
    - .inputrc
