---
- name: Install basic packages
  become: true
  ansible.builtin.package:
    name:
      - git
      - fuse-sshfs
      - tmux
      - vim
      - sway
    state: present

- name: Uninstall slop or fascist packages
  become: true
  ansible.builtin.package:
    name:
      - neovim
    state: absent

- name: Create .ssh dir
  ansible.builtin.file:
    path: '{{ ansible_facts["user_dir"] }}/.ssh'
    mode: "700"
    state: directory

- name: Generate ssh keys
  community.crypto.openssh_keypair:
    path: '{{ ansible_facts["user_dir"] }}/.ssh/id_rsa'
    type: rsa
    size: 4096
    state: present
    force: false

- name: Authorize ssh key to login to pi
  ansible.builtin.command:
    cmd: ssh-copy-id "{{ raspi_hostname }}"
  when: raspi_hostname is defined

- name: Set up sshfs remote
  ansible.builtin.template:
    src: remote.mount.j2
    dest: '{{ ansible_facts["user_dir"] }}/.config/systemd/user/home-{{ ansible_facts["user_id"] }}-remote.mount'
  when: raspi_hostname is defined

- name: Enable sshfs remote automount
  ansible.builtin.systemd:
    enabled: true
    unit: 'home-{{ ansible_facts["user_id"] }}-remote.mount'
    no_block: true
    scope: 'user'
    state: 'started'
  when: raspi_hostname is defined

- name: Set git configuration options
  community.general.ini_file:
    path: '{{ ansible_facts["user_dir"] }}/.gitconfig'
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: '644'
  loop:
    - section: core
      option: editor
      value: vim
    - section: branch
      option: sort
      value: "-committerdate"
    - section: tag
      option: sort
      value: "version:refname"
    - section: diff
      option: algorithm
      value: histogram
    - section: diff
      option: colorMoved
      value: plain
    - section: diff
      option: mnemonicPrefix
      value: "true"
    - section: diff
      option: renames
      value: "true"
    - section: push
      option: autoSetupRemote
      value: "true"
    - section: commit
      option: verbose
      value: "true"
  loop_control:
    label: "{{ item.section }}.{{ item.option }}"

- name: Install ALE
  ansible.builtin.git:
    depth: 1
    dest: '{{ ansible_facts["user_dir"] }}/.vim/pack/git-plugins/start/ale'
    repo: https://github.com/dense-analysis/ale.git

- name: Install TMux Plugin Manager
  ansible.builtin.git:
    depth: 1
    dest: '{{ ansible_facts["user_dir"] }}/.tmux/plugins/tpm'
    repo: https://github.com/tmux-plugins/tpm.git

- name: Copy dot files
  ansible.builtin.copy:
    src: "{{ file }}"
    dest: '{{ ansible_facts["user_dir"] }}/{{ file }}'
    mode: '644'
    backup: true
  loop_control:
    loop_var: "file"
  loop:
    - .vimrc
    - .tmux.conf
    - .bash_profile
    - .inputrc

- name: Copy sway config
  ansible.builtin.copy:
    src: sway_config
    dest: '{{ ansible_facts["user_dir"] }}/.config/sway/config'
    mode: '644'
    backup: true
