---
- name: Install basic packages
  become: yes
  package:
    name:
      - git
      - tmux
      - vim
    state: latest

- name: Generate ssh keys
  openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: no

- name: Make vim the default git editor
  community.general.ini_file:
      path: "{{ ansible_env.HOME }}/.gitconfig"
      section: core
      option: editor
      value: vim

- name: Install ALE
  git:
    depth: 1
    dest: "{{ ansible_env.HOME }}/.vim/pack/git-plugins/start/ale"
    repo: https://github.com/dense-analysis/ale.git

- name: Copy .vimrc
  copy:
    src: .vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: Copy .tmux.conf
  copy:
    src: .tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"

- name: Copy .bash_profile
  copy:
    src: .bash_profile
    dest: "{{ ansible_env.HOME }}/.bash_profile"
