---
- name: Install basic packages
  become: true
  ansible.builtin.package:
    name:
      - git
      - tmux
      - vim
    state: present

- name: Create .ssh dir
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    mode: "700"
    state: directory

- name: Generate ssh keys
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: false

- name: Install keybase (RPM)
  become: true
  ansible.builtin.dnf:
    name: https://prerelease.keybase.io/keybase_amd64.rpm
    state: present
  when:
    - ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat'
    - false

- name: Install keybase (DEB)
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - false
  block:
    - name: Download keybase (DEB)
      ansible.builtin.get_url:
        url: https://prerelease.keybase.io/keybase_amd64.deb
        dest: /tmp/keybase_amd64.deb
        mode: '600'

    - name: Install keybase (DEB)
      become: true
      ansible.builtin.apt:
        deb: /tmp/keybase_amd64.deb
        state: present

- name: Start keybase
  ansible.builtin.command:
    cmd: run_keybase -g
  when: false

- name: Make vim the default git editor
  community.general.ini_file:
    path: "{{ ansible_env.HOME }}/.gitconfig"
    section: core
    option: editor
    value: vim
    mode: '644'

- name: Install ALE
  ansible.builtin.git:
    depth: 1
    dest: "{{ ansible_env.HOME }}/.vim/pack/git-plugins/start/ale"
    repo: https://github.com/dense-analysis/ale.git

- name: Install TMux Plugin Manager
  ansible.builtin.git:
    depth: 1
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    repo: https://github.com/tmux-plugins/tpm.git

- name: Copy dot files
  ansible.builtin.copy:
    src: "{{ file }}"
    dest: "{{ ansible_env.HOME }}/{{ file }}"
    mode: '644'
  loop_control:
    loop_var: "file"
  loop:
    - .vimrc
    - .tmux.conf
    - .bash_profile
    - .inputrc
