---
- name: Install basic packages
  become: yes
  package:
    name:
      - fish
      - git
      - tmux
      - vim
    state: latest

- name: Create .ssh dir
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    mode: "700"
    state: directory

- name: Generate ssh keys
  openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: no

- name: Make vim the default git editor
  community.general.ini_file:
      path: "{{ ansible_env.HOME }}/.gitconfig"
      section: core
      option: editor
      value: vim

- name: Install ALE
  git:
    depth: 1
    dest: "{{ ansible_env.HOME }}/.vim/pack/git-plugins/start/ale"
    repo: https://github.com/dense-analysis/ale.git

- name: Copy .vimrc
  copy:
    src: .vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: Copy .tmux.conf
  copy:
    src: .tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"

- name: Copy .bash_profile
  copy:
    src: .bash_profile
    dest: "{{ ansible_env.HOME }}/.bash_profile"

- name: Run fish once to generate config files
  command:
    cmd: "fish -c 'sleep 2'"
    creates: "{{ ansible_env.HOME }}/.config/fish"

- name: Disable PWD truncation in fish
  lineinfile:
    line: "SETUVAR fish_prompt_pwd_dir_length:0"
    path: "{{ ansible_env.HOME }}/.config/fish/fish_variables"
    regex: "^SETUVAR fish_prompt_pwd_dir_length.*"
    state: present

- name: Set shell to fish
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: "/bin/fish"
