---
- name: Check if virtualization is enabled
  ansible.builtin.lineinfile:
    path: /proc/cpuinfo
    regexp: '(svm|vmx)'
    state: present
  check_mode: true
  register: virthost_presence
  failed_when: virthost_presence is changed

- name: Install virtualization packages
  become: true
  ansible.builtin.package:
    name:
      - libvirt-daemon
      - libvirt-daemon-kvm
      - qemu-kvm
      - vagrant
      - vagrant-sshfs
    state: present

- name: Get existing groups
  ansible.builtin.shell:
    cmd: cut -d ':' -f 1 /etc/group
  register: virthost_etc_groups
  changed_when: false

- name: Add virtualization groups to current user {{ ansible_facts["user_id"] }}
  become: true
  ignore_errors: true
  ansible.builtin.user:
    name: '{{ ansible_facts["user_id"] }}'
    groups: '{{ virthost_etc_groups.stdout_lines | ansible.builtin.intersect(virthost_groups) }}'
    append: true
  vars:
    virthost_groups:
      - kvm
      - qemu
      - libvirt
      - libvirt-qemu

- name: Start/enable virtualization daemon
  become: true
  ansible.builtin.service:
    enabled: true
    name: libvirtd
    state: started
