---
- name: Check if virtualization is enabled
  ansible.builtin.lineinfile:
    path: /proc/cpuinfo
    regexp: '(svm|vmx)'
    state: present
  check_mode: true
  register: presence
  failed_when: presence is changed

- name: Install virtualization packages
  become: true
  ansible.builtin.package:
    name:
      - libvirt-daemon
      - libvirt-daemon-kvm
      - qemu-kvm
      - vagrant
      - vagrant-sshfs
    state: present

- name: Add virtualization groups to current user {{ ansible_user_id }}
  become: true
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    groups:
      - kvm
    append: true

- name: Add qemu groups to current user {{ ansible_user_id }}
  become: true
  ignore_errors: true
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    groups:
      - "{{ group }}"
    append: true
  loop_control:
    loop_var: "group"
  loop:
    - qemu
    - libvirt
    - libvirt-qemu

- name: Start/enable virtualization daemon
  become: true
  ansible.builtin.service:
    enabled: true
    name: libvirtd
    state: started
